# Generated by Django 3.1.1 on 2020-09-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Услуга продления карты')),
                ('value', models.IntegerField(verbose_name='Срок продления в месяцах')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='CardStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Статус карты')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('fathers_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('phone', models.IntegerField(verbose_name='Контактный телефон')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubcard.sex', verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='ClubCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(unique=True, verbose_name='Номер клубной карты')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('balance', models.IntegerField(verbose_name='Суммарный баланс карты')),
                ('freeze_time', models.CharField(max_length=255, verbose_name='Замороженое время')),
                ('active_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubcard.activedate', verbose_name='Продление краты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubcard.cardcategory', verbose_name='Категория карты')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubcard.cardstatus', verbose_name='Статус карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubcard.user', verbose_name='Клиент')),
            ],
        ),
    ]
