# Generated by Django 3.1.1 on 2020-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubcard', '0002_auto_20200901_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcard',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Дата окончания абонемента'),
        ),
        migrations.AlterField(
            model_name='cardcategory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Категория карты'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Суммарный баланс карты'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='card_number',
            field=models.IntegerField(default=0, unique=True, verbose_name='Номер клубной карты'),
        ),
        migrations.AlterField(
            model_name='clubcard',
            name='freeze_time',
            field=models.CharField(default=0, max_length=255, verbose_name='Замороженое время'),
        ),
    ]
